blank_issues_enabled: true
contact_links:
  - name: "â” Start a Discussion"
    about: Ask a general question or start a discussion
    url: https://github.com/cssnr/hls-video-downloader/discussions/new?category=q-a

  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸ’» Visit Client Repository"
    about: Go to the native client source
    url: https://github.com/cssnr/hls-downloader-client

  - name: "ğŸŒ View Developer Site"
    about: Visit the developers website
    url: https://cssnr.github.io/
